name: CI/CD

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  analyse-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 safety pip-audit
          pip install pytest

      # Step 4: Flake8 linting
      - name: Flake8 lint
        run: |
          flake8 run.py
          flake8 app/db
          flake8 app/routes
          flake8 app/utils

      # Step 5: Safety check for known vulnerabilities - NOTE deprecated command
      - name: CVE safety check
        run: safety check --full-report

      # Step 6: Pip audit for CVEs
      - name: Pip CVE audit
        run: pip-audit

      # Step 7: Tests
      - name: Run unit tests
        run: pytest -v